### ISSUE TITLE
Bin indexes are not what they appear to be

### ISSUE THREAD

**Issue by wagoodman** [secnot/rectpack#15]
Given the example (run with python3):
```python
from rectpack import newPacker

rectangles = [(100, 30, 'aaa'), (40, 60, 'bbb'), (30, 30, 'ccc'),(70, 70, 'ddd'), (100, 50, 'eee'), (30, 30, 'fff')]
bins = [(100, 100), (80, 40), (80, 150)]

packer = newPacker()

# Add the rectangles to packing queue
for r in rectangles:
    packer.add_rect(*r)

# Add the bins where the rectangles will be placed
for b in bins:
    packer.add_bin(*b)

# Start packing
packer.pack()

# Full rectangle list
all_rects = packer.rect_list()
for rect in all_rects:
    b, x, y, w, h, rid = rect
    print(rect)
```

and the output:
```
(0, 0, 0, 100, 50, 'eee')
(0, 0, 50, 100, 30, 'aaa')
(1, 0, 0, 70, 70, 'ddd')
(1, 0, 70, 40, 60, 'bbb')
(1, 40, 70, 30, 30, 'ccc')
(1, 40, 100, 30, 30, 'fff')
```
It would seem that the solution is not possible. Bin 0 is nicely packed, no issue there. Bin 1 (80x40) is quite over-packed, and Bin 2 is never used.

Am I misinterpreting the bin indexes returned from `rect_list`?... meaning is bin index 1 actually Bin 2 and not Bin 1? Or is there an issue here?

**Comment by wagoodman** [comment]
Ok to answer my own question: yes, the bin indexes don't line up, but the application works fine. Here is a way to map back to the original bin indexes:

```python
from rectpack import newPacker

rectangles = [(100, 30, '100x30'), (100, 50, '100x50'), (40, 60, '40x60'), (30, 30, '30x30'),(70, 70, '70x70')]  #, (30, 30, 'fff'), (80, 150, 'ggg')]
bins = [(3,3, 't'),
        (100, 100, 'u'), 
        (80, 40, 'v'), 
        (2,2, 'w'), 
        (1, 1, 'x'), 
        (80, 150, 'y')]


packer = newPacker(rotation=False)

# Add the rectangles to packing queue
for r in rectangles:
    packer.add_rect(*r)

# Add the bins where the rectangles will be placed
for b in bins:
    packer.add_bin(*b[:-1])

# Start packing
packer.pack()


untouched_bins = list(packer._empty_bins.keys())
mapper = {}
for b in range(len(bins)):
    if b not in untouched_bins:
        print("%s --> %s" % (str(len(mapper)), str(b)))
        mapper[len(mapper)] = b
        

# touched_bins = len(packer._open_bins)
# for 
# while touched_bins > 0:


# Full rectangle list
all_rects = packer.rect_list()
for rect in all_rects:
    b, x, y, w, h, rid = rect
    #print("%s : %s" % (b, rid))
    print("%s : %s" % (str(bins[mapper[b]][-1]), str(rid)))
```

It would be nice to provide a convenience function to do this for you.

**Comment by wagoodman** [comment]
Indeed, getting exactly the bins back that were used for packing makes sense. However, if the bins represent a richer object, say a specific VM instance, then it is necessary to know which bins were used in the packing process. It would be ideal to either: 
a) allow bin IDs to be attached similar to how rect IDs are done (i.e. `bidx, bid, x, y, w, h, rid = rect`), or
b) make a convenience method that returns all of the bins in the same order they were given in,  so that they can be mapped back to the original higher-order objects.

**Comment by secnot** [comment]
Ok I see how it could be useful, but both solutions have problems in this cases:

```python
packer.add_bin(100, 200, count=20)
packer.add_bin(50, 60, count=float('Inf'))
```
But the first one is possible with the limitation that when several bins are added together all will have the same id.

```python
packer.add_bin(100, 200, count=20, bid=10)
```
Then you could do something like:
 
```python
for abin in packer:
    print(abin.bid)
    for rect in abin:
        print(rect)
```

**rect_list()** would only return the bin id when the bin has one to mantain backwards compatibility.

Correct me if I'm missing something else

**Comment by wagoodman** [comment]
I see your point about there being issues given your examples... with one more refinement a middle ground can be struck: bin id's don't matter when you provide 'count'.  This inherently invalidates the idea that bins have an id since the user hasn't provided these id's. This eliminates most of the issues mentioned, in which case `bid` could simply be assigned `None`.

Though this would break functionality for anyone explicitly unpacking a rect:
`bidx, x, y, w, h, rid = rect` vs `bidx, bid, x, y, w, h, rid = rect`

**Comment by secnot** [comment]
The simplest solution is to add the bin id with a default value of None, and to use the same id when several bins are added together. 

It is enough to write what you are looking for:

```python
def my_rect_list(packer):
        """
        Returns:
            List: Format [(rid, x, y, width, height, bid), ...]
        """
        rectangle_list = []
        for abin in packer:
            for rect in abin:
                rectangle_list.append((r.x, r.y, r.width, r.height, r.rid, abin.bid))

        return rectangle_list
```
but more importantly it won't break anything, so I can release it without having to test it for weeks.

It will probably be ready next week

**Comment by wagoodman** [comment]
Awesome! Thanks!

**Comment by secnot** [comment]
Done, I will need a little more time to upload it to pypi but it's already in the master branch.
