### ISSUE TITLE
example snippet for plotting the resulting layouts

### ISSUE THREAD

**Issue by koenhandekyn** [secnot/rectpack#16]
anyone willing to share an example snippet for plotting the resulting layouts or quick tip of library (new to python). if i'm correct i don't seem to find the snippet that generated the documentation drawings for example. thanks.

**Comment by secnot** [comment]
I can't find the code I used to generate the image, but I remember it used matplotlib. Here you have a link to a [small blog post](http://matthiaseisen.com/pp/patterns/p0203/) on how to use it to draw rectangles.

**Comment by koenhandekyn** [comment]
great thanks

**Comment by koenhandekyn** [comment]
snippet that draws up placement plans for all placed rectangles using matplotlib ( the bin size is scaled to square ) with thanks to the above snippet reference 

```
all_rects = packer.rect_list()

import matplotlib.pyplot as plt
import matplotlib.patches as patches

figs = [None] * nbins
axs = [None] * nbins
for rect in all_rects:
  b, x, y, w, h, rid = rect
  # b - Bin index
  # x - Rectangle bottom-left corner x coordinate
  # y - Rectangle bottom-left corner y coordinate
  # w - Rectangle width
  # h - Rectangle height
  # rid - User asigned rectangle id or None
  figs[b] = figs[b] or plt.figure()
  axs[b] = axs[b] or figs[b].add_subplot(111, aspect='equal')
  bw, bh = bins[b][0]*1.0, bins[b][1]*1.0
  print(w,h, 'in bin ', b, '=', bw, bh)
  axs[b].add_patch(
      patches.Rectangle(
          (x/bw, y/bh),  # (x,y)
          w/bw,          # width
          h/bh,          # height
          facecolor="#00ffff",
          edgecolor="black",
          linewidth=3
      )
  )
for index, fig in enumerate(figs):
  fig.savefig("rect_%(index)s.png" % locals(), dpi=90, bbox_inches='tight')

```

**Comment by secnot** [comment]
Thank you, I will keep it as a Gist until I have a few of them to add to the repository

**Comment by Adrian3652** [comment]
I guys, I have this error: __init__() missing 2 required positional arguments: 'width' and 'height'
At this line: 
ax.add_patch(
        patches.Rectangle(
            (x, y),  # (x,y)
            w,          # width
            h,          # height
            facecolor="#00ffff",
            edgecolor="black",
            linewidth=3)
How amI suppoused to solve this?

Thanks...

**Comment by Maralai** [comment]
After you have run packer.pack() you should be able to use this code (adapted from above) to step through each bin and fill in a rectangle on a 2D plot.

`	for index, abin in enumerate(packer):
		bw, bh  = abin.width, abin.height
		# print('bin', bw, bh, "nr of rectangles in bin", len(abin))

		fig = plt.figure()
		ax = fig.add_subplot(111, aspect='equal')
		for rect in abin:
			x, y, w, h = rect.x, rect.y, rect.width, rect.height
			plt.axis([0,bw,0,bh])
			# print('rectangle', w,h)
			patch = patches.Rectangle(
										(x, y),  # (x,y)
										w,          # width
										h,          # height
										facecolor="#00ffff",
										edgecolor="black",
										linewidth=3
									)
			# add the patch and get it's center
			ax.add_patch(patch)
			rx, ry = patch.get_xy()
			cx = rx + patch.get_width()/2.0
			cy = ry + patch.get_height()/2.0
			
			# drop anno in the center with width and height.
			ax.annotate(f'w:{w}\nh:{h}', (cx, cy), color='b', weight='bold', 
						fontsize=6, ha='center', va='center')
						
		fig.savefig(f"./Panel Optimization/{abin.bid}_{bw}x{bh}_{index+1}.png", 
				    dpi=1200, 
					papertype='letter',
					bbox_inches='tight')`

I had no issue with this implementation.

**Comment by Adrian3652** [comment]
When I run the code, I have another error: invalid syntax 
Line: ax.add_patch(patch)

What patch do I have to add? (# add the patch and get it's center)

Sorry, I'm really confused.

**Comment by Maralai** [comment]
I think you might be cutting pasting portions of the solutions and not the whole thing.

`
patches.Rectangle(
            (x, y),  # (x,y)
            w,          # width
            h,          # height
            facecolor="#00ffff",
            edgecolor="black",
            linewidth=3
`

**Comment by Maralai** [comment]
`import matplotlib.pyplot as plt
import matplotlib.patches as patches`

^ Sorry, I am wrong this was what your missing.

**Comment by Maralai** [comment]
I deleted my post earlier. I wanted to get the patch and it's center so i stored the return from patches.Rectangle(..) into a patch object then used that to get the center of the rectangle to put text there.

`patch = patches.Rectangle(
										(x, y),  # (x,y)
										w,          # width
										h,          # height
										facecolor="#00ffff",
										edgecolor="black",
										linewidth=3
									)
			ax.add_patch(patch)
			rx, ry = patch.get_xy()
			cx = rx + patch.get_width()/2.0
			cy = ry + patch.get_height()/2.0

			ax.annotate(f'w:{w}\nh:{h}', (cx, cy), color='b', weight='bold', 
						fontsize=4, ha='center', va='center')`

**Comment by Adrian3652** [comment]
[https://github.com/Adrian3652/2D-BPP/blob/master/README.md](url)

This is what I have, but I still can understand how to fill all the gaps. And also I don't know if this code is working as I wanted. Can you check my whole code and help me, please?
I've been working on this for 2 days and I'm stressed with all the commands and python stuff.
I really appreciate your previous help.

**Comment by Maralai** [comment]
> [https://github.com/Adrian3652/2D-BPP/blob/master/README.md](url)


The link is not working as expected.

**Comment by Maralai** [comment]
Got it.

**Comment by Maralai** [comment]
I looked over the script, it looks like indentation issues. I don't know how you are developing yet, but lower your barrier to entry with vscode and # %% for python interactive shell.

**Comment by Maralai** [comment]
Here is a minimally complete sample showing the results using your code:

```
from rectpack import newPacker
from matplotlib import pyplot as plt
import matplotlib.patches as patches

cajas = [(100, 30), (40, 60), (30, 30), (70, 70), (100, 50), (30, 30)]
contenedores = [(300, 450)]

packer = newPacker()

for c in cajas:
    packer.add_rect(*c)

for con in contenedores:
    packer.add_bin(*con)

packer.pack()

for index, abin in enumerate(packer):
    bw, bh  = abin.width, abin.height
    # print('bin', bw, bh, "nr of rectangles in bin", len(abin))

    fig = plt.figure()
    ax = fig.add_subplot(111, aspect='equal')
    for rect in abin:
        x, y, w, h = rect.x, rect.y, rect.width, rect.height
        plt.axis([0,bw,0,bh])
        # print('rectangle', w,h)
        patch = patches.Rectangle(
                                    (x, y),  # (x,y)
                                    w,          # width
                                    h,          # height
                                    facecolor="#00ffff",
                                    edgecolor="black",
                                    linewidth=3
                                )
        ax.add_patch(patch)
        rx, ry = patch.get_xy()
        cx = rx + patch.get_width()/2.0
        cy = ry + patch.get_height()/2.0

        ax.annotate(f'w:{w}\nh:{h}', (cx, cy), color='b', weight='bold', 
                    fontsize=4, ha='center', va='center')
                    
    fig.savefig(f"./Panel Optimization/{abin.bid}_{bw}x{bh}_{index+1}.png", 
                dpi=1200, 
                papertype='letter',
                bbox_inches='tight')
```

**Comment by Adrian3652** [comment]
OMG!!! That's amazing.
You really help me a lot with this, I have no words, really really thanks!!! :'D

I have literally read about 20 forums trying to see where I was wrong, but it became too difficult to try to solve it.

Thanks!! Really.
