### ISSUE TITLE
Plotting output?

### ISSUE THREAD

**Issue by LittleDavid** [secnot/rectpack#21]
How do I get the output to be a plot as shown in the introduction page?

**Comment by secnot** [comment]
Hi

Already answered [here](https://github.com/secnot/rectpack/issues/16), but in short using matplotlib.

**Comment by LittleDavid** [comment]
Thank you!
Sorry for spamming: should I delete this?

**Comment by secnot** [comment]
Leave it, probably someone else will find it useful :).

**Comment by thoka** [comment]
should be closed?

**Comment by secnot** [comment]
A year is probably enough :)
