### ISSUE TITLE
Restrict number of bins

### ISSUE THREAD

**Issue by florianbepunkt** [secnot/rectpack#25]
I would like to use this for an optimization case to see how many boxes fit on one pallet.

Is there a way to have a fixed number of bins (in my case 1) and to get a result if the packed boxes fit?

Or simpler: I have pack items of the same size and I would like to get a packing schema and an answer how many boxes will fit in 1 bin.

**Comment by secnot** [comment]
Yes, add a single bin and more rectangles than the area of the bin.

Try several algorithms and the one that packs the most packages is your solution.

But if all the packages are of the same size, I'm sure there are better algorithms to do it than the ones in the library.

**Comment by florianbepunkt** [comment]
@secnot Thank you. Thought so too, but actually the default algorithm performs quite well compared to http://lagrange.ime.usp.br/~lobato/packing/run/index.php

**Comment by secnot** [comment]
If you don't need to generate the partitioning for every pallet, you could try one of the exact algorithms, for example:

Kathryn A. Dowsland - An exact algorithm for the pallet loading problem

it should be around 5% more efficient, but much slower. It all depends on how important is to lower the shipping costs I suppose

Good luck

**Comment by florianbepunkt** [comment]
@secnot do you know by chance whether a pythin implementation of an exact algorithm existst?

**Comment by secnot** [comment]
No, I don't remember any, perhaps there is a c++ library that you can interface from python.
