### ISSUE TITLE
How to print an image with the rectangles placed in the bin?

### ISSUE THREAD

**Issue by Adrian3652** [secnot/rectpack#31]
I need to print the image with the rectangles that are gonna be placed in the bin. 
I'm a beginner with python, that's why I dont know how to print what I need.

**Comment by secnot** [comment]
Hi

I think the simplest method is using matplotlib, there is an example in [this other issue](https://github.com/secnot/rectpack/issues/16)

**Comment by Adrian3652** [comment]
Thanks!!, but know I have another problem.
I have a problem with this line 

ax.add_patch(
        patches.Rectangle(

When I run it, it says "Name " patches" is not defined. 

Can you help me? please.
