### ISSUE TITLE
Packer not working when coverage is 75% or higher.

### ISSUE THREAD

**Issue by Merthew** [secnot/rectpack#37]
So I am using this library to try and pack rectangles (go figure) into a single bin. It works completely fine for my test of 25% coverage as well as my test for 50% coverage. However, it runs into issues when I try to use my 75% and 95% tests. At the moment I am assuming that I am somehow using this package wrong, but I would like to have some input. I am using python 3 for this if that makes any difference.

[code.txt](https://github.com/secnot/rectpack/files/4472305/code.txt)

**Comment by don-eng** [comment]
Hi,
I am using this and have packing coverage ranging from 10% if not enough
parts to 98+% for densely populated sheets so i know the library works.   A
quick look at your code did not show me anything obvious.

Please include your input file.

Thanks

Donald Fast
https://www.linkedin.com/in/donaldfast/

**Comment by Merthew** [comment]
Here are the input files.
[25PercentFill.txt](https://github.com/secnot/rectpack/files/4472352/25PercentFill.txt)
[50PercentFill.txt](https://github.com/secnot/rectpack/files/4472353/50PercentFill.txt)
[75PercentFill.txt](https://github.com/secnot/rectpack/files/4472354/75PercentFill.txt)
[95PercentFill.txt](https://github.com/secnot/rectpack/files/4472355/95PercentFill.txt)

**Comment by don-eng** [comment]
Hi Timothy,

1) I don't see that you specify packing method and i don't know what the
default is.
If it is a guillotine cut, i don't think you can get all those pieces onto
1 sheet/canvas.
i have the line:

PMODE = PackingMode.Offline
# pbin options: MaxRectsBlsf  MaxRectsBaf MaxRectsBssf MaxRectsBl (others
not defined)
# SkylineWMixin SkylineMwf SkylineMwfl SkylineBl (others not defined)
# GuillotineMinas  GuillotineMaxas GuillotineLlas GuillotineBssf (and
more...)
PBIN = MaxRectsBl

# sort options: SORT_AREA  SORT_DIFF  SORT_LSIDE SORT_NONE
# SORT_PERI SORT_RATIO SORT_SSIDE
PSORT = packer.SORT_AREA

packer = newPacker(mode=PMODE, rotation=allowRotn,  pack_algo=PBIN,
sort_algo=PSORT)


2) Do you only want one sheet packed?  If you want more, use a line of code
like,
       canvasSize = [(sheetX, sheetY, float("inf"))]
       packer.add_bin(*canvasSize)

**Comment by Merthew** [comment]
At one time I only need to pack into one bin, which is why I only have the one packer.add_bin(*canvasSize) line.
As for defaults, I shouldn't need to beyond allowing rotation.

**Comment by Merthew** [comment]
I also get this error when trying that line: AttributeError: 'PackerBBF' object has no attribute 'SORT_AREA'

**Comment by secnot** [comment]
Just tested the inputs, using the same packing parameters.

95PercentilFill -> 91.57% of the bin is filled
75PercentilFill -> 74.9% of the bin is filled

I don't see anything wrong with the library.

```python
import sys
from rectpack import newPacker


def load_file(path):
    fd = open(str(sys.argv[1]), 'r')
    lines = fd.readlines()
    return [(int(l.split(',')[0]), int(l.split(',')[1])) for l in lines]


def main():
    lines = load_file(str(sys.argv[1]))

    # Load rectangles
    canvas = lines[0]
    rectangles = lines[1:]

    # Pack into canvas
    packer = newPacker()
    packer.add_bin(canvas[0], canvas[1])
    for r in rectangles:
        packer.add_rect(r[0], r[1])

    packer.pack()

    # Check how much area was filled
    area_filled = sum([w*h for _, _, _, w, h, _ in packer.rect_list()])
    total_area = canvas[0]*canvas[1]
    print(100*area_filled/total_area, '%')

main()
```
