### ISSUE TITLE
BinBestFit not utilizing all given bins, just open bins.

### ISSUE THREAD

**Issue by stedingan** [secnot/rectpack#38]
Hello,

i would like to discuss the following piece of code.

```
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from rectpack import newPacker, PackingMode, MaxRectsBl, PackingBin, SORT_NONE, SORT_AREA


def LPack():
    packer = newPacker(mode=PackingMode.Offline, bin_algo=PackingBin.BFF, pack_algo=MaxRectsBl, sort_algo=SORT_NONE)
    width = 700
    height = 500
    packer.add_bin(width=width, height=height)
    packer.add_bin(width=width, height=height)

    packer.add_rect(700, 300)
    packer.add_rect(100, 200)
    packer.add_rect(300, 300)
    packer.add_rect(100, 200)
    packer.add_rect(200, 300)
    packer.add_rect(200, 300)
    packer.add_rect(100, 200)

    packer.pack()

    fig = plt.figure(figsize=(20, 20))
    ax = [fig.add_subplot(2, 2, 1, aspect='equal'),
          fig.add_subplot(2, 2, 2, aspect='equal'),
          fig.add_subplot(2, 2, 3, aspect='equal'),
          fig.add_subplot(2, 2, 4, aspect='equal'),
          ]

    for ix, a in enumerate(ax):
        a.set_xlim(0, width)
        a.set_ylim(0, height)
        a.add_patch(patches.Rectangle((0, 0), width=width, height=height, color='white', fill=False))
        if ix in [0, 1]:
            a.title.set_text('Implemented BinBestFit')
        else:
            a.title.set_text('Expected BinBestFit')


    for ix, rect in enumerate(packer.rect_list()):
        b, x, y, w, h, rid = rect

        rect = patches.Rectangle((float(x), float(y)), width=float(w), height=float(h))
        ax[b].add_patch(rect)
        ax[b].plot(float(x), float(y), 'o', color='red', mew=3, ms=3)

    expected = [
        (2, 0, 0, 700, 300),
        (2, 0, 300, 200, 100),
        (3, 0, 0, 200, 100),
        (3, 200, 0, 300, 300),
        (3, 500, 0, 200, 100),
        (3, 0, 100, 200, 300),
        (3, 500, 100, 200, 300),
    ]

    for e in expected:
        b, x, y, w, h = e
        rect = patches.Rectangle((float(x), float(y)), width=float(w), height=float(h), color="red")
        ax[b].add_patch(rect)
        ax[b].plot(float(x), float(y), 'x', color='black', mew=3, ms=3)

    plt.show()


LPack()
```

As you can see I use the *bin_algo=PackingBin.BBF*. Looking at the resulting plots from *BFF* and *BBF* I was confused because they are the same. This made me curious, so i debugged a bit and it seems like you are just using the open_bins to evaluate the BinBestFit. Is this intended?

I expected with a BinBestFit approach that the packing would consider all bins right away for placing a rect. In the code fragment above I also inserted the packing I'd expected and added a plot.
![img-2020-05-01-165014](https://user-images.githubusercontent.com/22867893/80814363-0879a300-8bcc-11ea-8ec9-f581d9b5c309.png)

 What do you think about this?

Have a good weekend and thank you for your work.

**Comment by secnot** [comment]
Hi

BBF packs the rectangle into the open bin with best fitness, if it doesn't fit into any of the open ones it will try the closed bins.

If all the bins (open and close) where checked, for example if you had 20 bins and 20 rectangles each rectangle would end alone in one bin. What you suggest works great when the total area or the rectangles is near or greater than the total area of the bins (specially if you sort the rectangles), but not so great in the general case.

Perhaps a custom mode ABBF (All Bin Best Fit) could be useful for some cases.

I hope that that is what you were asking for.

**Comment by stedingan** [comment]
Hello secnot,

thanks for the fast and detailed reply.
Okay, right that's what I also suspected. Even tho I think that it's more a matter of online vs. offline packing I see the use cases of the implemented BBF heuristic. This will also minimize the difference in between BFF and BBF because a new bins will just be used if a rectangle does not fit. 

Thanks again.

**Comment by secnot** [comment]
A useful strategy is to open another closed bin as soon as the emptiest of the open ones is 50% or 75% filled, it needs to be tunned depending on the rectangles/bins relative sizes but can give good results when the rectangles are sorted and there is mix of big and small.

**Comment by stedingan** [comment]
Oh that's also a neat parameter idea. I'll go play around with it for some time.
Also closing the ticket, I think the BBF is clear now. Thanks again.
