### ISSUE TITLE
How to have a unsorted packed list

### ISSUE THREAD

**Issue by ShaunKulesa** [secnot/rectpack#46]
When I pack the rectangles it returns a list of rectangles ordered in order of where they are placed in, but because I'm using this for a texture atlas I still need to know which file name is for each rectangle. Is there a way to return the list in the order I entered the rectangles details in?

`rectangles = [(200, 100), (400, 100), (300, 100)]`

instead of `[[0, 0, 400, 100], [400, 0, 300, 100], [700, 0, 200, 100]]`

I want it in the order I put it in `[[700, 0, 200, 100], [0, 0, 400, 100], [400, 0, 300, 100]]` so I can compare them with my list of file paths.

**Comment by ShaunKulesa** [comment]
found it in the source,
 I think this is correct, 
![image](https://user-images.githubusercontent.com/69469909/145028698-b87bf43b-2494-4283-bbb0-e750650a8291.png)

**Comment by secnot** [comment]
That's it :+1:
